import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json([
    {
      id: 1,
      name: "Smartphone X23",
      price: 699.99,
      description:
        "The latest flagship smartphone with a stunning display and advanced camera features.",
      category: "Electronics",
      brand: "Brand A",
      stock: 50,
    },
    {
      id: 2,
      name: "Laptop ProBook 15",
      price: 1199.99,
      description:
        "Powerful laptop for professionals with a sleek design and long-lasting battery.",
      category: "Electronics",
      brand: "Brand B",
      stock: 20,
    },
    {
      id: 3,
      name: "Cotton T-Shirt",
      price: 19.99,
      description:
        "Comfortable and stylish cotton t-shirt available in various colors and sizes.",
      category: "Apparel",
      brand: "Brand C",
      stock: 100,
    },
    {
      id: 4,
      name: "Leather Wallet",
      price: 39.99,
      description:
        "Handcrafted leather wallet with multiple card slots and RFID protection.",
      category: "Accessories",
      brand: "Brand D",
      stock: 30,
    },
    {
      id: 5,
      name: "Wireless Earbuds",
      price: 79.99,
      description:
        "High-quality wireless earbuds with noise-cancellation and long battery life.",
      category: "Electronics",
      brand: "Brand E",
      stock: 60,
    },
    {
      id: 6,
      name: "Fitness Tracker Watch",
      price: 49.99,
      description:
        "Stay fit and active with this feature-rich fitness tracker watch.",
      category: "Electronics",
      brand: "Brand F",
      stock: 25,
    },
    {
      id: 7,
      name: "Organic Coffee Beans",
      price: 12.99,
      description:
        "Premium organic coffee beans sourced from sustainable farms.",
      category: "Food & Beverages",
      brand: "Brand G",
      stock: 80,
    },
    {
      id: 8,
      name: "Bluetooth Speaker",
      price: 59.99,
      description:
        "Portable Bluetooth speaker with 360-degree sound and water resistance.",
      category: "Electronics",
      brand: "Brand H",
      stock: 40,
    },
    {
      id: 9,
      name: "Scented Soy Candle",
      price: 24.99,
      description: "Hand-poured scented soy candle with a soothing fragrance.",
      category: "Home & Living",
      brand: "Brand I",
      stock: 35,
    },
    {
      id: 10,
      name: "Men's Leather Jacket",
      price: 199.99,
      description: "Stylish and durable men's leather jacket for all seasons.",
      category: "Apparel",
      brand: "Brand J",
      stock: 15,
    },
    {
      id: 11,
      name: "Digital Camera",
      price: 499.99,
      description:
        "High-resolution digital camera with advanced image stabilization.",
      category: "Electronics",
      brand: "Brand K",
      stock: 18,
    },
    {
      id: 12,
      name: "Reusable Water Bottle",
      price: 14.99,
      description:
        "Eco-friendly reusable water bottle made from stainless steel.",
      category: "Accessories",
      brand: "Brand L",
      stock: 90,
    },
    {
      id: 13,
      name: "Wireless Gaming Mouse",
      price: 79.99,
      description: "Precision gaming mouse with customizable RGB lighting.",
      category: "Electronics",
      brand: "Brand M",
      stock: 22,
    },
    {
      id: 14,
      name: "Women's Running Shoes",
      price: 89.99,
      description: "Comfortable and supportive running shoes for women.",
      category: "Footwear",
      brand: "Brand N",
      stock: 30,
    },
    {
      id: 15,
      name: "Portable Power Bank",
      price: 39.99,
      description:
        "Compact and high-capacity power bank for charging on-the-go.",
      category: "Electronics",
      brand: "Brand O",
      stock: 50,
    },
    {
      id: 16,
      name: "Stainless Steel Kitchen Set",
      price: 129.99,
      description: "Complete kitchen set made from durable stainless steel.",
      category: "Home & Kitchen",
      brand: "Brand P",
      stock: 10,
    },
    {
      id: 17,
      name: "Gaming Headset",
      price: 69.99,
      description:
        "Immersive gaming headset with noise-cancellation and surround sound.",
      category: "Electronics",
      brand: "Brand Q",
      stock: 25,
    },
    {
      id: 18,
      name: "Eco-Friendly Bamboo Toothbrush",
      price: 9.99,
      description: "Biodegradable and sustainable toothbrush made from bamboo.",
      category: "Personal Care",
      brand: "Brand R",
      stock: 120,
    },
    {
      id: 19,
      name: "Professional Chef's Knife",
      price: 89.99,
      description: "Premium-quality chef's knife for culinary experts.",
      category: "Home & Kitchen",
      brand: "Brand S",
      stock: 15,
    },
    {
      id: 20,
      name: "HD Smart TV",
      price: 799.99,
      description:
        "Smart TV with high-definition display and streaming capabilities.",
      category: "Electronics",
      brand: "Brand T",
      stock: 8,
    },
    {
      id: 21,
      name: "Hiking Backpack",
      price: 79.99,
      description:
        "Durable and spacious hiking backpack with multiple compartments.",
      category: "Outdoor Gear",
      brand: "Brand U",
      stock: 40,
    },
    {
      id: 22,
      name: "Noise-Canceling Headphones",
      price: 149.99,
      description:
        "Premium noise-canceling headphones for a distraction-free experience.",
      category: "Electronics",
      brand: "Brand V",
      stock: 30,
    },
    {
      id: 23,
      name: "Scented Bath Bombs",
      price: 14.99,
      description:
        "Relaxing scented bath bombs for a spa-like experience at home.",
      category: "Personal Care",
      brand: "Brand W",
      stock: 70,
    },
    {
      id: 24,
      name: "Automatic Espresso Machine",
      price: 399.99,
      description: "Semi-automatic espresso machine for coffee enthusiasts.",
      category: "Appliances",
      brand: "Brand X",
      stock: 12,
    },
    {
      id: 25,
      name: "Yoga Mat",
      price: 29.99,
      description:
        "Non-slip and eco-friendly yoga mat for a comfortable workout.",
      category: "Fitness & Sports",
      brand: "Brand Y",
      stock: 20,
    },
    {
      id: 26,
      name: "Smartwatch",
      price: 149.99,
      description:
        "Feature-rich smartwatch with health monitoring and notification support.",
      category: "Electronics",
      brand: "Brand Z",
      stock: 50,
    },
    {
      id: 27,
      name: "Leather Handbag",
      price: 199.99,
      description:
        "Elegant leather handbag with multiple compartments and a stylish design.",
      category: "Accessories",
      brand: "Brand AA",
      stock: 30,
    },
    {
      id: 28,
      name: "Bluetooth Earphones",
      price: 49.99,
      description:
        "Wireless Bluetooth earphones with a comfortable fit and long battery life.",
      category: "Electronics",
      brand: "Brand BB",
      stock: 40,
    },
    {
      id: 29,
      name: "Outdoor Camping Tent",
      price: 129.99,
      description:
        "Spacious and weather-resistant camping tent for outdoor adventures.",
      category: "Outdoor Gear",
      brand: "Brand CC",
      stock: 15,
    },
    {
      id: 30,
      name: "Polaroid Instant Camera",
      price: 79.99,
      description: "Capture memories instantly with this fun polaroid camera.",
      category: "Electronics",
      brand: "Brand DD",
      stock: 20,
    },
    {
      id: 31,
      name: "Organic Herbal Tea",
      price: 9.99,
      description: "Refreshing organic herbal tea with various flavors.",
      category: "Food & Beverages",
      brand: "Brand EE",
      stock: 80,
    },
    {
      id: 32,
      name: "Wireless Gaming Controller",
      price: 69.99,
      description: "Responsive gaming controller for console and PC gaming.",
      category: "Electronics",
      brand: "Brand FF",
      stock: 25,
    },
    {
      id: 33,
      name: "Recycled Notebook Set",
      price: 12.99,
      description:
        "Eco-friendly notebook set made from recycled paper with unique designs.",
      category: "Office Supplies",
      brand: "Brand GG",
      stock: 35,
    },
    {
      id: 34,
      name: "Women's Winter Coat",
      price: 149.99,
      description:
        "Stylish and warm winter coat for women's cold weather fashion.",
      category: "Apparel",
      brand: "Brand HH",
      stock: 18,
    },
    {
      id: 35,
      name: "Portable Solar Charger",
      price: 49.99,
      description: "Solar-powered charger for charging devices on-the-go.",
      category: "Electronics",
      brand: "Brand II",
      stock: 30,
    },
    {
      id: 36,
      name: "Essential Oil Diffuser",
      price: 24.99,
      description: "Aromatherapy diffuser with soothing LED lights.",
      category: "Home & Living",
      brand: "Brand JJ",
      stock: 25,
    },
    {
      id: 37,
      name: "Classic Men's Watch",
      price: 89.99,
      description: "Timeless and elegant watch for men.",
      category: "Accessories",
      brand: "Brand KK",
      stock: 90,
    },
    {
      id: 38,
      name: "Portable Blender",
      price: 29.99,
      description: "Compact blender for smoothies and shakes on-the-go.",
      category: "Appliances",
      brand: "Brand LL",
      stock: 22,
    },
    {
      id: 39,
      name: "Fitness Resistance Bands",
      price: 19.99,
      description: "Versatile resistance bands for effective workouts at home.",
      category: "Fitness & Sports",
      brand: "Brand MM",
      stock: 30,
    },
    {
      id: 40,
      name: "Stainless Steel Water Bottle",
      price: 14.99,
      description: "Durable and reusable stainless steel water bottle.",
      category: "Accessories",
      brand: "Brand NN",
      stock: 70,
    },
    {
      id: 41,
      name: "Foldable Electric Scooter",
      price: 349.99,
      description:
        "Convenient and eco-friendly electric scooter for urban commuting.",
      category: "Electronics",
      brand: "Brand OO",
      stock: 12,
    },
    {
      id: 42,
      name: "Plant-Based Protein Powder",
      price: 29.99,
      description: "Nutritious and delicious plant-based protein powder.",
      category: "Food & Beverages",
      brand: "Brand PP",
      stock: 20,
    },
    {
      id: 43,
      name: "Smart Home Security Camera",
      price: 89.99,
      description: "Wireless smart camera for home security and monitoring.",
      category: "Electronics",
      brand: "Brand QQ",
      stock: 50,
    },
    {
      id: 44,
      name: "Natural Bath Sponge",
      price: 9.99,
      description: "Gentle and biodegradable natural bath sponge.",
      category: "Personal Care",
      brand: "Brand RR",
      stock: 40,
    },
    {
      id: 45,
      name: "Men's Dress Shoes",
      price: 79.99,
      description:
        "Stylish and comfortable dress shoes for men's formal occasions.",
      category: "Footwear",
      brand: "Brand SS",
      stock: 15,
    },
    {
      id: 46,
      name: "Home Security Alarm System",
      price: 199.99,
      description:
        "Comprehensive home security alarm system with smartphone app control.",
      category: "Electronics",
      brand: "Brand TT",
      stock: 8,
    },
    {
      id: 47,
      name: "Reusable Silicone Food Bags",
      price: 19.99,
      description: "Eco-friendly and reusable silicone food bags.",
      category: "Home & Kitchen",
      brand: "Brand UU",
      stock: 40,
    },
    {
      id: 48,
      name: "Gaming Keyboard",
      price: 89.99,
      description: "Mechanical gaming keyboard with customizable RGB lighting.",
      category: "Electronics",
      brand: "Brand VV",
      stock: 30,
    },
    {
      id: 49,
      name: "Scented Body Lotion",
      price: 12.99,
      description: "Hydrating scented body lotion with nourishing ingredients.",
      category: "Personal Care",
      brand: "Brand WW",
      stock: 60,
    },
    {
      id: 50,
      name: "Electric Toothbrush",
      price: 39.99,
      description: "Powerful electric toothbrush for effective oral care.",
      category: "Personal Care",
      brand: "Brand XX",
      stock: 25,
    },
    {
      id: 51,
      name: "Outdoor Portable Grill",
      price: 149.99,
      description:
        "Compact and portable grill for outdoor cooking and picnics.",
      category: "Outdoor Gear",
      brand: "Brand YY",
      stock: 20,
    },
    {
      id: 52,
      name: "Solar-Powered LED Lights",
      price: 29.99,
      description: "Decorative and energy-efficient solar-powered LED lights.",
      category: "Home & Living",
      brand: "Brand ZZ",
      stock: 35,
    },
    {
      id: 53,
      name: "Women's Leather Wallet",
      price: 49.99,
      description: "Stylish and functional leather wallet for women.",
      category: "Accessories",
      brand: "Brand AAA",
      stock: 18,
    },
    {
      id: 54,
      name: "Wireless Charging Pad",
      price: 24.99,
      description: "Qi-enabled wireless charging pad for compatible devices.",
      category: "Electronics",
      brand: "Brand BBB",
      stock: 30,
    },
    {
      id: 55,
      name: "Herbal Shampoo",
      price: 14.99,
      description: "Natural and nourishing herbal shampoo for healthy hair.",
      category: "Personal Care",
      brand: "Brand CCC",
      stock: 50,
    },
    {
      id: 56,
      name: "Reusable Beeswax Wraps",
      price: 19.99,
      description: "Eco-friendly beeswax wraps for sustainable food storage.",
      category: "Home & Kitchen",
      brand: "Brand DDD",
      stock: 40,
    },
    {
      id: 57,
      name: "Indoor Plants Set",
      price: 39.99,
      description: "Assortment of beautiful and easy-care indoor plants.",
      category: "Home & Living",
      brand: "Brand EEE",
      stock: 15,
    },
    {
      id: 58,
      name: "Wireless Charging Stand",
      price: 34.99,
      description:
        "Multi-functional wireless charging stand for smartphones and accessories.",
      category: "Electronics",
      brand: "Brand FFF",
      stock: 50,
    },
    {
      id: 59,
      name: "Yoga Blocks",
      price: 12.99,
      description: "Supportive yoga blocks for better flexibility and posture.",
      category: "Fitness & Sports",
      brand: "Brand GGG",
      stock: 25,
    },
    {
      id: 60,
      name: "Home Office Desk",
      price: 199.99,
      description: "Stylish and functional home office desk for remote work.",
      category: "Furniture",
      brand: "Brand HHH",
      stock: 20,
    },
    {
      id: 61,
      name: "Himalayan Salt Lamp",
      price: 29.99,
      description:
        "Natural and soothing Himalayan salt lamp for ambiance and air purification.",
      category: "Home & Living",
      brand: "Brand III",
      stock: 30,
    },
    {
      id: 62,
      name: "Vegan Leather Backpack",
      price: 49.99,
      description: "Fashionable and cruelty-free vegan leather backpack.",
      category: "Accessories",
      brand: "Brand JJJ",
      stock: 35,
    },
    {
      id: 63,
      name: "Smart Thermostat",
      price: 79.99,
      description:
        "Energy-efficient smart thermostat for precise temperature control.",
      category: "Electronics",
      brand: "Brand KKK",
      stock: 18,
    },
    {
      id: 64,
      name: "Stainless Steel Mixing Bowls",
      price: 24.99,
      description: "Durable and versatile stainless steel mixing bowls.",
      category: "Home & Kitchen",
      brand: "Brand LLL",
      stock: 30,
    },
    {
      id: 65,
      name: "Inflatable Stand-Up Paddleboard",
      price: 299.99,
      description:
        "Portable and inflatable stand-up paddleboard for water sports.",
      category: "Outdoor Gear",
      brand: "Brand MMM",
      stock: 25,
    },
    {
      id: 66,
      name: "Silicone Baking Mat Set",
      price: 19.99,
      description:
        "Non-stick silicone baking mat set for easy baking and cleanup.",
      category: "Home & Kitchen",
      brand: "Brand NNN",
      stock: 22,
    },
    {
      id: 67,
      name: "Aromatherapy Essential Oils Set",
      price: 39.99,
      description: "Variety pack of pure aromatherapy essential oils.",
      category: "Personal Care",
      brand: "Brand OOO",
      stock: 30,
    },
    {
      id: 68,
      name: "Professional Hair Dryer",
      price: 69.99,
      description:
        "Powerful and salon-quality hair dryer for quick drying and styling.",
      category: "Personal Care",
      brand: "Brand PPP",
      stock: 50,
    },
    {
      id: 69,
      name: "Ceramic Cookware Set",
      price: 129.99,
      description:
        "High-quality and non-toxic ceramic cookware set for healthy cooking.",
      category: "Home & Kitchen",
      brand: "Brand QQQ",
      stock: 12,
    },
    {
      id: 70,
      name: "Polarized Sunglasses",
      price: 29.99,
      description: "Stylish and polarized sunglasses for UV protection.",
      category: "Accessories",
      brand: "Brand RRR",
      stock: 20,
    },
    {
      id: 71,
      name: "Air Purifier",
      price: 89.99,
      description: "Efficient air purifier for clean and fresh indoor air.",
      category: "Appliances",
      brand: "Brand SSS",
      stock: 40,
    },
    {
      id: 72,
      name: "Hammock",
      price: 49.99,
      description: "Relaxing hammock for outdoor leisure and relaxation.",
      category: "Outdoor Gear",
      brand: "Brand TTT",
      stock: 30,
    },
    {
      id: 73,
      name: "Scented Soy Wax Melts",
      price: 9.99,
      description: "Fragrant soy wax melts for a pleasant aroma at home.",
      category: "Home & Living",
      brand: "Brand UUU",
      stock: 70,
    },
    {
      id: 74,
      name: "Handheld Vacuum Cleaner",
      price: 39.99,
      description:
        "Portable and cordless handheld vacuum cleaner for quick cleaning.",
      category: "Appliances",
      brand: "Brand VVV",
      stock: 12,
    },
    {
      id: 75,
      name: "Dumbbell Set",
      price: 79.99,
      description: "Adjustable dumbbell set for versatile strength training.",
      category: "Fitness & Sports",
      brand: "Brand WWW",
      stock: 18,
    },
    {
      id: 76,
      name: "Stylish Watch Box",
      price: 29.99,
      description: "Elegant watch box for storing and displaying timepieces.",
      category: "Accessories",
      brand: "Brand XXX",
      stock: 25,
    },
    {
      id: 77,
      name: "Portable Espresso Maker",
      price: 49.99,
      description: "Compact and manual espresso maker for coffee on the go.",
      category: "Appliances",
      brand: "Brand YYY",
      stock: 30,
    },
    {
      id: 78,
      name: "Aloe Vera Gel",
      price: 14.99,
      description: "Soothing and hydrating aloe vera gel for skin care.",
      category: "Personal Care",
      brand: "Brand ZZZ",
      stock: 60,
    },
  ]);
}
